In [9]:
from tensorflow.keras.preprocessing.text import one_hot

In [10]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [11]:
voc_size = 10000
## one hot representation --- 1 - voc-size 
onehot_repr=[one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[8150, 8132, 5810, 7950], [8150, 8132, 5810, 9289], [8150, 995, 5810, 3698], [3924, 1996, 3742, 3804, 9553], [3924, 1996, 3742, 3804, 1912], [214, 8150, 2467, 5810, 6232], [3797, 4943, 5649, 3804]]


In [12]:
from tensorflow.keras.layers import Embedding
##pad seq -- make sure that vector are of same length
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [13]:
sent_length=8
embedded_docs = pad_sequences(onehot_repr,
                              padding='pre',
                              maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 8150 8132 5810 7950]
 [   0    0    0    0 8150 8132 5810 9289]
 [   0    0    0    0 8150  995 5810 3698]
 [   0    0    0 3924 1996 3742 3804 9553]
 [   0    0    0 3924 1996 3742 3804 1912]
 [   0    0    0  214 8150 2467 5810 6232]
 [   0    0    0    0 3797 4943 5649 3804]]


8

In [17]:
#dimension of embedding vector = 10 
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')


c:\Users\jaikr\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [18]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)