In [ ]:
##categorical data to numerical data into a binary vector represntation


##each unique word in your vocabulary is assigned a unique number
## a word is then represnted 
##---> 1 if the word is present in the sentence
##---> 0 if the word is not present in the sentence

In [ ]:
# ["I","am","learning","NLP"] -- words 

##step 1 -- is to find all the unique words in your vocabulary
# I                               - [1,0,0,0]
# am                               -[0,1,0,0]
# learning                         -[0,0,1,0]
# NLP                              -[0,0,0,1]

In [ ]:
#sparse matrix -- a matrix where most of the elements are zero
#dense matrix -- a matrix where most of the elements are non-zero

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

words = np.array(["I","love","NLP"]).reshape(-1,1)
#sparse_output is used in old version of scikit learn
##sparse is used in new version of scikit learn 
encoder = OneHotEncoder(sparse_output=False)

one_hot = encoder.fit_transform(words)

print(one_hot)


[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
